---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/illuminati/data":
    get:
      summary: get data
      responses:
        '200':
          description: successful
    post:
      summary: post data
      parameters: []
      responses:
        '200':
          description: successful
        '400':
          description: error
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                schedules:
                  type: array
                  items:
                    type: object
                    properties:
                      starting_period:
                        type: string
                      ending_period:
                        type: string
                      group_name:
                        type: string
              required:
              - title
              - content
  "/api/illuminati/groups":
    get:
      summary: get an array of unique groups
      responses:
        '200':
          description: successful
  "/api/slamdunk/upvote":
    parameters:
    - id: id
      in: path
      required: true
      schema:
        type: integer
    get:
      summary: increment upvotes
      responses:
        '200':
          description: successful
  "/api/slamdunk/downvote":
    parameters:
    - id: id
      in: path
      required: true
      schema:
        type: integer
    get:
      summary: increment downvotes
      responses:
        '200':
          description: successful
servers:
- url: https://{defaultHost}
  variables:
    defaultHost:
      default: hackforsrilanka-api.herokuapp.com/
