---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/illuminati/data":
    get:
      summary: get data
      tags:
      - Illuminati
      responses:
        '200':
          description: successful
    post:
      summary: post data
      tags:
      - Illuminati
      parameters: []
      responses:
        '200':
          description: successful
        '400':
          description: error
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                schedules:
                  type: array
                  items:
                    type: object
                    properties:
                      starting_period:
                        type: string
                      ending_period:
                        type: string
                      group_name:
                        type: string
              required:
              - title
              - content
  "/api/illuminati/groups":
    get:
      summary: get an array of unique groups
      tags:
      - Illuminati
      responses:
        '200':
          description: successful
  "/api/illuminati/powerschedules/{group_name}":
    get:
      summary: get power schedules between start and end times
      tags:
      - Illuminati
      parameters:
      - name: group_name
        in: path
        required: true
        schema:
          type: string
      - name: start_date
        in: query
        format: date_time
        schema:
          type: string
      - name: end_date
        in: query
        format: date_time
        schema:
          type: string
      responses:
        '200':
          description: successful
        '400':
          description: error
  "/api/slamdunk/submit":
    post:
      summary: increment upvotes
      tags:
      - Slam Dunk
      parameters: []
      responses:
        '200':
          description: successful
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                station_id:
                  type: integer
                  required: true
                gas_type:
                  type: string
                  enum:
                  - petrol_93
                  - diesel
                  - petrol_95
                  - gas_cylinder
                  - super_diesel
                  required: true
                availability:
                  type: string
                  enum:
                  - available
                  - unavailable
                  - unsure
                  required: true
                wait_time:
                  type: integer
                submitted_at:
                  type: string
                  required: true
  "/api/slamdunk/upvote/{id}":
    parameters:
    - id: id
      in: path
      required: true
      schema:
        type: integer
    post:
      summary: increment upvotes
      tags:
      - Slam Dunk
      responses:
        '200':
          description: successful
  "/api/slamdunk/downvote/{id}":
    parameters:
    - id: id
      in: path
      required: true
      schema:
        type: integer
    post:
      summary: increment downvotes
      tags:
      - Slam Dunk
      responses:
        '200':
          description: successful
servers:
- url: https://{defaultHost}
  variables:
    defaultHost:
      default: hackforsrilanka-api.herokuapp.com/
- url: http://localhost:3000
