---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/test":
    get:
      summary: list tests
      responses:
        '200':
          description: successful
servers:
- url: https://{defaultHost}
  variables:
    defaultHost:
      default: hackforsrilanka-api.herokuapp.com/
